--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/deceitya/RunRun
build-by-default: true
branches:
- master
projects:
  RunRun:
    path: ""
    libs:
      - src: FlowyProject/Flowy/Flowy
      - src: CortexPE/Commando/Commando
...
